package main

import (
	"context"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

// SWE-bench-specific harness extension: after a patch.diff is judged OK by
// the critic, run the project's own test suite for the modified module.
//
// Rationale: smoke30 (n=30) showed 10/22 failures were patches the critic
// approved (`ok=true`) but hidden tests rejected. The hidden tests ARE the
// project's pytest files — running them directly is the strongest alignment
// signal. Multiple iterations of prompt-level "MANDATORY pytest" language
// were ignored by Qwen3.5-122B-A10B (verified via 0 pytest invocations
// across 3 rerun batches), so this gate is enforced harness-side.
//
// Activated by `--swe-pytest-gate` flag OR `BANYA_SWE_BENCH=1` env var.

// extractPatchedFiles reads a unified diff and returns the list of post-image
// file paths (the "+++ b/<path>" lines, normalized to drop the "b/" prefix).
func extractPatchedFiles(patchPath string) []string {
	data, err := os.ReadFile(patchPath)
	if err != nil {
		return nil
	}
	var files []string
	for _, line := range strings.Split(string(data), "\n") {
		if !strings.HasPrefix(line, "+++ ") {
			continue
		}
		p := strings.TrimSpace(strings.TrimPrefix(line, "+++ "))
		// Strip "b/" prefix that git diff uses; ignore /dev/null deletions.
		if p == "/dev/null" {
			continue
		}
		p = strings.TrimPrefix(p, "b/")
		files = append(files, p)
	}
	return files
}

// findTestFilesForModule searches the repo for pytest files corresponding to
// each modified source file. Returns paths relative to the repo root, suitable
// for `pytest <path>` invocation.
//
// Heuristic order (first match wins per source file):
//  1. <dir>/tests/test_<basename>.py
//  2. <dir>/../tests/test_<basename>.py
//  3. <repo>/tests/test_<basename>.py
//  4. Recursive find for test_<basename>.py anywhere under repo
//
// Files outside `repo/` (e.g. workspace-level repro.py) are skipped — only
// changes to the project source tree generate test invocations.
func findTestFilesForModule(workDir string, patchedFiles []string) []string {
	repoRoot := filepath.Join(workDir, "repo")
	seen := map[string]bool{}
	var hits []string

	for _, p := range patchedFiles {
		// patch.diff is generated by `cd repo && git diff` so paths are
		// relative to repo/ (no leading "repo/"). Strip leading "repo/" if
		// present (defensive — older harness versions used workspace-relative
		// paths). Skip workspace-level helper files the agent creates.
		fname := filepath.Base(p)
		if fname == "repro.py" || fname == "patch.diff" || fname == "plan.md" || strings.HasPrefix(fname, "repro_") {
			continue
		}
		relInRepo := strings.TrimPrefix(p, "repo/")
		if !strings.HasSuffix(relInRepo, ".py") {
			continue
		}
		base := strings.TrimSuffix(filepath.Base(relInRepo), ".py")
		dir := filepath.Dir(relInRepo)
		candidates := []string{
			filepath.Join(dir, "tests", "test_"+base+".py"),
			filepath.Join(filepath.Dir(dir), "tests", "test_"+base+".py"),
			filepath.Join("tests", "test_"+base+".py"),
		}
		matched := ""
		for _, c := range candidates {
			abs := filepath.Join(repoRoot, c)
			if st, err := os.Stat(abs); err == nil && !st.IsDir() {
				matched = c
				break
			}
		}
		if matched == "" {
			// Fallback: walk the repo and grab the first test_<base>.py.
			target := "test_" + base + ".py"
			_ = filepath.Walk(repoRoot, func(path string, info os.FileInfo, err error) error {
				if err != nil || matched != "" || info.IsDir() {
					return nil
				}
				if info.Name() == target {
					rel, rerr := filepath.Rel(repoRoot, path)
					if rerr == nil {
						matched = rel
					}
				}
				return nil
			})
		}
		if matched != "" && !seen[matched] {
			seen[matched] = true
			hits = append(hits, matched)
		}
	}
	return hits
}

// runProjectPytest invokes pytest on each test file (sequentially, stop on
// first failure within a file via -x). Returns (allPassed, combinedOutput).
// Output is truncated to ~80 lines per failing file to keep the revise prompt
// manageable for a slow-LLM context.
func runProjectPytest(ctx context.Context, workDir string, testFiles []string, timeoutS int) (bool, string) {
	repoRoot := filepath.Join(workDir, "repo")
	var combined strings.Builder
	allPassed := true

	for _, tf := range testFiles {
		cmd := exec.CommandContext(ctx, "python", "-m", "pytest", tf, "-x", "--tb=short", "--no-header", "-q")
		cmd.Dir = repoRoot
		out, err := cmd.CombinedOutput()
		passed := err == nil
		if !passed {
			allPassed = false
		}
		combined.WriteString(fmt.Sprintf("=== pytest %s ===\n", tf))
		// Trim very long output — keep only last 80 lines so the revise prompt
		// stays focused on the failure tail.
		lines := strings.Split(string(out), "\n")
		if len(lines) > 80 {
			lines = append([]string{fmt.Sprintf("... [%d earlier lines elided] ...", len(lines)-80)}, lines[len(lines)-80:]...)
		}
		combined.WriteString(strings.Join(lines, "\n"))
		if !passed {
			combined.WriteString(fmt.Sprintf("\n[exit: %v]\n", err))
		}
		combined.WriteString("\n")
	}
	return allPassed, combined.String()
}

// buildPytestRevisePrompt frames the failure output as a revise instruction
// to the agent. Mirrors the critic-revise wording so the agent can react in
// the same way.
func buildPytestRevisePrompt(testFiles []string, output string) string {
	files := strings.Join(testFiles, ", ")
	return "PROJECT-PYTEST FAILED. Your patch broke pre-existing tests in " + files + ".\n" +
		"This is the same test suite the SWE-bench harness uses for hidden test verification — fix it now or lose the task.\n\n" +
		"Pytest output (tail):\n" +
		"```\n" + strings.TrimSpace(output) + "\n```\n\n" +
		"Revise your patch to fix the failures. Then regenerate patch.diff:\n" +
		"  cd repo && git add -A && git diff --cached > ../patch.diff && git restore --staged .\n\n" +
		"Re-verify with both your reproducer (run_reproducer) AND pytest before finishing."
}
